apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: service-weather
  namespace: greetings-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: greetings-app
    subApp: greetings-channel
spec:
  template:
    kind: Service
    apiVersion: v1
    metadata:
      name: weather
      namespace: greetings-app-ns
      labels:
        app: greetings-app
        subApp: greetings-channel        
        comp: weather
    spec:
      type: NodePort
      ports:
        - name: my-http
          port: 9091
          nodePort: 32421
      selector:
        app: greetings-app
        subApp: greetings-channel        
        comp: weather
