apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: greetings
  namespace: greetings-subscription-ns
  labels:
    app: greetings-app
    subApp: greetings-subscription
spec:
  clusterReplicas: 1
  clusterLabels:
    matchLabels:
      cloud: IBM
      region: Baletowa
#---
#cloud=IBM
#environment=ST_DMZ
#name=spx-ocp-c02
#region=Baletowa
#---
#environment=ST_CORP
#name=spx-ocp-c01
#region=Grodzisk
