apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: greetings
  namespace: greetings-subscription-ns
  labels:
    app: greetings-app
    subApp: greetings-subscription
spec:
  channel: greetings-channel-ns/greetings
  placement:
    placementRef:
      name: greetings
      kind: PlacementRule
      group: app.ibm.com
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: greetings-app-ns